name: Promote

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.4.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: false
          reviewers: false
          labels: ""
          blocking_labels: ""
          checks_enabled: true
          method: squash
          delete_source_branch: true
  release:
    needs: promote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Generate Timestamp
        id: tstamp
        run: |
          echo "::set-output name=epochdate::$(date +%s)"
          echo "::set-output name=semverdate::$(date +%Y%m%d.%H%M.%S)"
      - name: Place Timestamp As Serial Number
        run: |
          cd $GITHUB_WORKSPACE/etc/bind/
          echo ${{steps.tstamp.outputs.epochdate}}
          cat hitoma.com.db
          sed -i 's/SERIALNUMBERPLACEHOLDER/${{steps.tstamp.outputs.epochdate}}/g' *
          cat hitoma.com.db
      - name: Make Archive
        run: |
          cd $GITHUB_WORKSPACE
          mkdir builds
          tar -czvf builds/zones.tar.gz ./etc
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: 'DNS Zones v${{ steps.tstamp.outputs.semverdate }}.${{ steps.tstamp.outputs.epochdate }}'
          files: |
            builds/zones.tar.gz
      - name: Timestamp debug
        run: |
          echo ${{steps.tstamp.outputs.epochdate}}
