# This is a basic workflow to help you get started with Actions

name: Verify and Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Merge in from develop
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "shawngmc@gmail.com"
          git config user.name "Shawn McNaughton (Github Action)"
          git remote update
          git fetch
          mkdir ../tmp/
          cp -R * ../tmp/
          git checkout main
          cp -R ../tmp/* ./

      - name: Get timestamp for serial number
        id: tstamp
        run: echo "::set-output name=date::$(date +%s)"
      
      - name: Place serial number
        run: |
          cd $GITHUB_WORKSPACE/etc/bind
          sed -i 's/SERIALNUMBERPLACEHOLDER/${{steps.tstamp.outputs.date}}/g' *

      - name: Install bind packages
        run: sudo apt install bind9 bind9utils

      - name: Verify DNS entry validity
        run: $GITHUB_WORKSPACE/scripts/validate.sh

      - name: Push the verified zones to main
        run: |
          cd $GITHUB_WORKSPACE
          git commit -a -m "Pushing verified zones ${{steps.tstamp.outputs.date}}"
          git tag -a "v${{steps.tstamp.outputs.date}}" -m "Verified release ${{steps.tstamp.outputs.date}}"
          git push --tags
          